/** Actions const */
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USER_TASKS_SUCCESS = "LOAD_USER_TASKS_SUCCESS";
export const CHANGE_SELECTED_USER = "CHANGE_SELECTED_USER";
