/** Actions const */
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USER_TASKS_SUCCESS = "LOAD_USER_TASKS_SUCCESS";

export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_TASKS_SUCCESS = "CREATE_USER_TASKS_SUCCESS";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_TASKS_SUCCESS = "UPDATE_USER_TASKS_SUCCESS";

export const DELETE_USER_SUCCESS = "DELETE_USERS_SUCCESS";
export const DELETE_USER_TASK_SUCCESS = "DELETE_USER_TASKS_SUCCESS";

export const CHANGE_SELECTED_USER = "CHANGE_SELECTED_USER";
export const EMPTY_TASK_STORE = "EMPTY_TASK_STORE";
