/** Actions const */
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const UPDATE_SELECTED_PRODUCT = "UPDATE_SELECTED_PRODUCT";
export const ADD_PRODUCT_TO_SHOPPING_CART_SUCCESS =
  "ADD_PRODUCT_TO_SHOPPING_CART_SUCCESS";
export const DELETE_PRODUCT_FROM_SHOPPING_CART_SUCCESS =
  "DELETE_PRODUCT_FROM_SHOPPING_CART_SUCCESS";
